# Generated by Django 4.2.7 on 2026-05-10 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NBA Fantasy 2024-25', max_length=100)),
                ('season', models.CharField(default='2024-25', max_length=10)),
                ('budget_cap', models.IntegerField(default=100000000)),
                ('max_players', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('total_score', models.FloatField(default=0.0)),
                ('total_spent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='predictor.fantasyleague')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='FantasyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('team_code', models.CharField(max_length=5)),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center'), ('BENCH', 'Bench')], default='BENCH', max_length=6)),
                ('salary', models.IntegerField(default=0)),
                ('fantasy_score', models.FloatField(default=0.0)),
                ('pts', models.FloatField(default=0)),
                ('ast', models.FloatField(default=0)),
                ('reb', models.FloatField(default=0)),
                ('stl', models.FloatField(default=0)),
                ('blk', models.FloatField(default=0)),
                ('tov', models.FloatField(default=0)),
                ('fg_pct', models.FloatField(default=0)),
                ('three_pct', models.FloatField(default=0)),
                ('ft_pct', models.FloatField(default=0)),
                ('mp', models.FloatField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='predictor.fantasyteam')),
            ],
            options={
                'ordering': ['-fantasy_score'],
                'unique_together': {('team', 'player_name')},
            },
        ),
    ]
